<a href="https://colab.research.google.com/github/GRIETIOTLAB/EdgeComputingWS/blob/main/Python%20Basics/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Hello World**

In [ ]:
print('Hello World!')

Hello World!


**Variables**

In [ ]:
# A variable stores a piece of data and gives it a name

a = 42

# a contained an integer bcos we gave it an integer

is_it_monday = True
is_it_sunday = False

# booleans example

pi_approx = 3.1415

# float example

my_name = "Murthy"

# String data type

print(pi_approx)
print(my_name)


3.1415
Murthy


**Lists**

In [ ]:
prices = [10,20,30,40,50]

colors= ["red","blue","yellow"]

mixed_list= [1,2.2,"three",False]

print(prices)

print(colors[0])

print(mixed_list[3])

[10, 20, 30, 40, 50]
red
False


**Importing in Python**

In [ ]:
float1 = 5.24
float2 = 2.25

import math
print(math.log(float1))
print(math.exp(float2))

import matplotlib.pyplot as plt
x = [-2,-1,0,1,2]
y = [-4,-2,0,2,4]
plt.plot(x,y)

**Loops**

In [ ]:
fib = [1,1,2,3,5,8]

for i in range(0,len(fib)):
  print(fib[i])

print("Let's try again")

for j in fib:
  print(j)

**Conditionals**

In [ ]:
answer = 47

if answer == 42:
  print("This is the answer to the ultimate question")
elif answer < 42:
  print("This is less than the answer to the ultimate question")
else:
  print("This is more than the answer to the ultimate question")
print("This is always printed")



This is more than the answer to the ultimate question
This is always printed


**Functions**

In [ ]:
def print_me(s):
  print(s)
  return

print_me("Hello World")

def step(x):
  if (x < 0):
    return -1
  elif (x >= 0):
    return 1

print(step(2))
print(step(-5))



Hello World
1
-1


**Numpy arrays**

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([9,8,7])

# Be careful with syntax. the parantheses and brackets are both required
print(a)

print(a[0])

#Element-wise operations

c = a + b
d = a - b
e = a * b
f = a / b

print(c)
print(d)
print(e)
print(f)

In [ ]:
import numpy as np
np.array([1,4,6,5,3])

array([1, 4, 6, 5, 3])

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.random.random((3,3))

array([[0.81397968, 0.0967989 , 0.26866963],
       [0.04172395, 0.78459406, 0.23697102],
       [0.5736828 , 0.19348312, 0.69153236]])